"""create relationship between category and sub channel

Revision ID: f48f6a0e5385
Revises: 358e2db2c8f4
Create Date: 2022-10-28 15:50:39.257764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48f6a0e5385'
down_revision = '358e2db2c8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_channels', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscription_channels', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_channels', type_='foreignkey')
    op.drop_column('subscription_channels', 'category_id')
    # ### end Alembic commands ###
